[0m
[0m
[2A[0m[0m[2K[0m[32m[1m+ [0m[1mGet all deployment configurations[0m
[0m[2K[0m  [0mSuccess[0m[0m
[32m[1m+ [0mRetrieved all deployments.[0m[0m
- name: default
  version: ''
  providers:
    appengine:
      enabled: false
      accounts: []
      primaryAccount: null
      gcloudPath: null
    aws:
      enabled: false
      accounts: []
      primaryAccount: null
      bakeryDefaults:
        templateFile: null
        baseImages: []
        awsAccessKey: null
        awsSecretKey: null
        awsSubnetId: null
        awsVpcId: null
        awsAssociatePublicIpAddress: null
        defaultVirtualizationType: null
      accessKeyId: null
      secretAccessKey: null
      defaultAssumeRole: null
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
      primaryAccount: null
      awsAccount: null
    azure:
      enabled: false
      accounts: []
      primaryAccount: null
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      primaryAccount: null
      clusters: []
    dockerRegistry:
      enabled: false
      accounts: []
      primaryAccount: null
    google:
      enabled: false
      accounts: []
      primaryAccount: null
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        networkProjectId: null
        useInternalIp: false
      defaultRegions: null
    kubernetes:
      enabled: false
      accounts: []
      primaryAccount: null
    oracle:
      enabled: false
      accounts: []
      primaryAccount: null
      bakeryDefaults:
        templateFile: oci.json
        baseImages: []
        availabilityDomain: null
        subnetId: null
        instanceShape: null
    cloudfoundry:
      enabled: false
      accounts: []
      primaryAccount: null
  deploymentEnvironment:
    size: SMALL
    type: LocalDebian
    accountName: null
    bootstrapOnly: null
    updateVersions: true
    consul:
      address: null
      enabled: false
    vault:
      address: null
      enabled: false
    location: null
    customSizing: {}
    sidecars: {}
    initContainers: {}
    hostAliases: {}
    affinity: {}
    nodeSelectors: {}
    gitConfig:
      upstreamUser: spinnaker
      originUser: null
    livenessProbeConfig:
      enabled: false
      initialDelaySeconds: null
    haServices:
      clouddriver:
        enabled: false
        redisMasterEndpoint: null
        redisSlaveEndpoint: null
        redisSlaveDeckEndpoint: null
        disableClouddriverRoDeck: false
      echo:
        enabled: false
  persistentStorage:
    persistentStoreType: null
    azs:
      storageAccountName: null
      storageAccountKey: null
      storageContainerName: null
    gcs:
      jsonPath: null
      project: null
      bucket: null
      rootFolder: front50
      bucketLocation: null
    redis:
      host: null
      port: null
    s3:
      bucket: null
      rootFolder: front50
      region: null
      pathStyleAccess: null
      endpoint: null
      accessKeyId: null
      secretAccessKey: null
    oracle: {}
  features:
    auth: false
    fiat: false
    chaos: false
    entityTags: false
    jobs: false
    pipelineTemplates: null
    artifacts: null
    mineCanary: null
    appengineContainerImageUrlDeployments: null
    infrastructureStages: null
    travis: null
    wercker: null
    managedPipelineTemplatesV2UI: null
    gremlin: null
  metricStores:
    datadog:
      enabled: false
      api_key: null
      app_key: null
      tags: []
    prometheus:
      enabled: false
      push_gateway: null
      add_source_metalabels: true
    stackdriver:
      enabled: false
      project: null
      zone: null
      credentials_path: null
      instance_id: null
    period: 30
    enabled: false
  notifications:
    slack:
      enabled: false
      botName: null
      token: null
    twilio:
      enabled: false
      account: null
      baseUrl: https://api.twilio.com/
      from: null
      token: null
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: false
      masters: []
    travis:
      enabled: false
      masters: []
    wercker:
      enabled: false
      masters: []
    concourse:
      enabled: false
      masters: []
    gcb:
      enabled: false
      accounts: []
  repository:
    artifactory:
      enabled: false
      searches: []
  security:
    apiSecurity:
      ssl:
        enabled: false
        keyAlias: null
        keyStore: null
        keyStoreType: null
        keyStorePassword: null
        trustStore: null
        trustStoreType: null
        trustStorePassword: null
        clientAuth: null
      overrideBaseUrl: null
      corsAccessPattern: null
    uiSecurity:
      ssl:
        enabled: false
        sslCertificateFile: null
        sslCertificateKeyFile: null
        sslCACertificateFile: null
        sslCertificatePassphrase: null
      overrideBaseUrl: null
    authn:
      oauth2:
        enabled: false
        client:
          clientId: null
          clientSecret: null
          accessTokenUri: null
          userAuthorizationUri: null
          clientAuthenticationScheme: null
          scope: null
          preEstablishedRedirectUri: null
          useCurrentUri: null
        userInfoRequirements: null
        resource:
          userInfoUri: null
        userInfoMapping:
          email: null
          firstName: null
          lastName: null
          username: null
        provider: null
      saml:
        enabled: false
        metadataLocal: null
        metadataRemote: null
        issuerId: null
        keyStore: null
        keyStorePassword: null
        keyStoreAliasName: null
        serviceAddress: null
        userAttributeMapping:
          firstName: null
          lastName: null
          roles: null
          rolesDelimiter: null
          username: null
      ldap:
        enabled: false
        url: null
        userDnPattern: null
        userSearchBase: null
        userSearchFilter: null
        managerDn: null
        managerPassword: null
        groupSearchBase: null
      x509:
        enabled: false
        roleOid: null
        subjectPrincipalRegex: null
      iap:
        enabled: false
        jwtHeader: null
        issuerId: null
        audience: null
        iapVerifyKeyUrl: null
      enabled: false
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
          credentialPath: null
          adminUsername: null
          domain: null
        github:
          roleProviderType: GITHUB
          baseUrl: null
          accessToken: null
          organization: null
        file:
          roleProviderType: FILE
          path: null
        ldap:
          roleProviderType: LDAP
          url: null
          managerDn: null
          managerPassword: null
          userDnPattern: null
          userSearchBase: null
          groupSearchBase: null
          userSearchFilter: null
          groupSearchFilter: null
          groupRoleAttributes: null
      enabled: false
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    oracle:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    gitlab:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    helm:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []
    maven:
      enabled: false
      accounts: []
    templates: []
  pubsub:
    enabled: false
    google:
      enabled: false
      pubsubType: GOOGLE
      subscriptions: []
      publishers: []
  canary:
    enabled: false
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
      metadataCachingIntervalMS: null
    - name: prometheus
      enabled: false
      accounts: []
      metadataCachingIntervalMS: null
    - name: datadog
      enabled: false
      accounts: []
    - name: signalfx
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    reduxLoggerEnabled: true
    defaultMetricsAccount: null
    defaultStorageAccount: null
    defaultJudge: NetflixACAJudge-v1.0
    defaultMetricsStore: null
    stagesEnabled: true
    atlasWebComponentsUrl: null
    templatesEnabled: true
    showAllConfigsEnabled: true
  webhook:
    trust:
      enabled: false
      trustStore: null
      trustStorePassword: null
[0m
